import os
import sys
import queue
import threading
import traceback
from pathlib import Path
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from tkinter.scrolledtext import ScrolledText

import extract_prc
import Main_PRC


class QueueWriter:
    """Redirect print output from a worker thread into the Tkinter log safely."""

    def __init__(self, message_queue, stream_name="stdout"):
        self.message_queue = message_queue
        self.stream_name = stream_name

    def write(self, text):
        if text:
            self.message_queue.put((self.stream_name, text))
        return len(text)

    def flush(self):
        return None

    def isatty(self):
        return False


class PRCAutomationUI(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("PRC Factsheet Automation (By SS)")
        self.geometry("980x720")
        self.minsize(860, 620)

        self.events = queue.Queue()
        self.worker = None

        self.input_folder = tk.StringVar()
        self.image_folder = tk.StringVar(
            value=str((Path.cwd() / "Automated_image_data").resolve())
        )
        self.scheme_master = tk.StringVar()
        self.fund_column = tk.StringVar(value="Fund Name")
        self.excel_output = tk.StringVar(
            value=str((Path.cwd() / "PRC_Output_Final_Detailed.xlsx").resolve())
        )
        self.zoom = tk.DoubleVar(value=3.0)
        self.debug = tk.BooleanVar(value=True)
        self.status = tk.StringVar(value="Ready")

        self._build_ui()
        self.after(100, self._drain_events)
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _build_ui(self):
        style = ttk.Style(self)
        if "clam" in style.theme_names():
            style.theme_use("clam")
        style.configure("Title.TLabel", font=("Segoe UI", 18, "bold"))
        style.configure("Sub.TLabel", font=("Segoe UI", 10))
        style.configure("Run.TButton", font=("Segoe UI", 10, "bold"), padding=8)

        outer = ttk.Frame(self, padding=16)
        outer.pack(fill="both", expand=True)

        ttk.Label(outer, text="PRC Factsheet Automation", style="Title.TLabel").pack(anchor="w")
        ttk.Label(
            outer,
            text="Step 1 crops PRC images from factsheet PDFs. Step 2 reads the images and creates the final Excel output.",
            style="Sub.TLabel",
        ).pack(anchor="w", pady=(2, 14))

        form = ttk.LabelFrame(outer, text="Input and output settings", padding=12)
        form.pack(fill="x")
        form.columnconfigure(1, weight=1)

        self._folder_row(
            form, 0, "Factsheet folder:", self.input_folder,
            self._browse_input_folder,
            "Select the root folder containing AMC subfolders/PDF factsheets."
        )
        self._folder_row(
            form, 1, "Extracted image folder:", self.image_folder,
            self._browse_image_folder,
            "PRC crops generated by extract_prc.py will be stored here."
        )
        self._file_row(
            form, 2, "Scheme master (optional):", self.scheme_master,
            self._browse_scheme_master,
            "Optional Excel/CSV scheme master used for fund-name mapping."
        )
        self._file_row(
            form, 3, "Final Excel output:", self.excel_output,
            self._browse_excel_output,
            "Main_PRC.py writes the Final and Detailed sheets here."
        )

        ttk.Label(form, text="Master fund column:").grid(row=4, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Entry(form, textvariable=self.fund_column).grid(row=4, column=1, sticky="ew", pady=6)

        options = ttk.Frame(form)
        options.grid(row=5, column=1, sticky="w", pady=(5, 0))
        ttk.Label(options, text="PDF render zoom:").pack(side="left")
        ttk.Spinbox(options, from_=1.0, to=8.0, increment=0.5, width=7, textvariable=self.zoom).pack(side="left", padx=(6, 20))
        ttk.Checkbutton(options, text="Save OCR debug images", variable=self.debug).pack(side="left")

        actions = ttk.Frame(outer)
        actions.pack(fill="x", pady=12)

        self.run_all_button = ttk.Button(
            actions, text="Run complete pipeline", style="Run.TButton",
            command=lambda: self._start("all")
        )
        self.run_all_button.pack(side="left")

        self.extract_button = ttk.Button(
            actions, text="1. Extract images only",
            command=lambda: self._start("extract")
        )
        self.extract_button.pack(side="left", padx=8)

        self.ocr_button = ttk.Button(
            actions, text="2. Generate Excel only",
            command=lambda: self._start("ocr")
        )
        self.ocr_button.pack(side="left")

        ttk.Button(actions, text="Clear log", command=self._clear_log).pack(side="right")

        progress_frame = ttk.Frame(outer)
        progress_frame.pack(fill="x", pady=(0, 8))
        self.progress = ttk.Progressbar(progress_frame, mode="indeterminate")
        self.progress.pack(side="left", fill="x", expand=True)
        ttk.Label(progress_frame, textvariable=self.status, width=24, anchor="e").pack(side="right", padx=(10, 0))

        log_frame = ttk.LabelFrame(outer, text="Live processing log", padding=8)
        log_frame.pack(fill="both", expand=True)
        self.log = ScrolledText(
            log_frame, wrap="word", font=("Consolas", 9),
            state="disabled", background="#101418", foreground="#d8e1e8",
            insertbackground="white"
        )
        self.log.pack(fill="both", expand=True)
        self.log.tag_configure("stderr", foreground="#ff8a80")
        self.log.tag_configure("success", foreground="#7ee787")
        self.log.tag_configure("info", foreground="#79c0ff")

    def _folder_row(self, parent, row, label, variable, command, help_text):
        ttk.Label(parent, text=label).grid(row=row, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Entry(parent, textvariable=variable).grid(row=row, column=1, sticky="ew", pady=6)
        ttk.Button(parent, text="Browse...", command=command).grid(row=row, column=2, padx=(8, 0), pady=6)
        ttk.Label(parent, text=help_text, foreground="#666666").grid(row=row + 10, column=1, sticky="w")

    def _file_row(self, parent, row, label, variable, command, help_text):
        ttk.Label(parent, text=label).grid(row=row, column=0, sticky="w", padx=(0, 10), pady=6)
        ttk.Entry(parent, textvariable=variable).grid(row=row, column=1, sticky="ew", pady=6)
        ttk.Button(parent, text="Browse...", command=command).grid(row=row, column=2, padx=(8, 0), pady=6)

    def _browse_input_folder(self):
        path = filedialog.askdirectory(title="Select factsheet root folder")
        if path:
            self.input_folder.set(path)

    def _browse_image_folder(self):
        path = filedialog.askdirectory(title="Select extracted image output folder", mustexist=False)
        if path:
            self.image_folder.set(path)

    def _browse_scheme_master(self):
        path = filedialog.askopenfilename(
            title="Select scheme master",
            filetypes=[("Excel/CSV files", "*.xlsx *.xls *.csv"), ("All files", "*.*")]
        )
        if path:
            self.scheme_master.set(path)

    def _browse_excel_output(self):
        path = filedialog.asksaveasfilename(
            title="Save final PRC Excel file",
            defaultextension=".xlsx",
            filetypes=[("Excel workbook", "*.xlsx")],
            initialfile="PRC_Output_Final_Detailed.xlsx"
        )
        if path:
            self.excel_output.set(path)

    def _validate(self, mode):
        input_dir = Path(self.input_folder.get().strip()) if self.input_folder.get().strip() else None
        image_dir = Path(self.image_folder.get().strip()) if self.image_folder.get().strip() else None
        master = Path(self.scheme_master.get().strip()) if self.scheme_master.get().strip() else None
        excel = Path(self.excel_output.get().strip()) if self.excel_output.get().strip() else None

        if mode in ("all", "extract") and (input_dir is None or not input_dir.is_dir()):
            raise ValueError("Please select a valid factsheet folder.")
        if image_dir is None:
            raise ValueError("Please select an extracted image folder.")
        if mode == "ocr" and not image_dir.is_dir():
            raise ValueError("The selected extracted image folder does not exist.")
        if master is not None and not master.is_file():
            raise ValueError("The selected scheme master file does not exist.")
        if mode in ("all", "ocr"):
            if excel is None:
                raise ValueError("Please select the final Excel output file.")
            if excel.suffix.lower() != ".xlsx":
                excel = excel.with_suffix(".xlsx")
                self.excel_output.set(str(excel))
        if not self.fund_column.get().strip():
            raise ValueError("Master fund column cannot be blank.")
        if float(self.zoom.get()) <= 0:
            raise ValueError("Zoom must be greater than zero.")

        return (
            input_dir, image_dir, master, excel,
            float(self.zoom.get()), self.fund_column.get().strip(), bool(self.debug.get())
        )

    def _start(self, mode):
        if self.worker and self.worker.is_alive():
            messagebox.showinfo("Already running", "A PRC job is already running.")
            return

        try:
            settings = self._validate(mode)
        except Exception as exc:
            messagebox.showerror("Invalid settings", str(exc))
            return

        self._set_running(True)
        self._append_log(f"\n--- Starting {mode.upper()} job ---\n", "info")
        self.worker = threading.Thread(
            target=self._run_worker,
            args=(mode, settings),
            daemon=True,
            name="PRCWorker"
        )
        self.worker.start()

    def _run_worker(self, mode, settings):
        input_dir, image_dir, master, excel, zoom, fund_column, debug = settings
        old_stdout, old_stderr = sys.stdout, sys.stderr
        sys.stdout = QueueWriter(self.events, "stdout")
        sys.stderr = QueueWriter(self.events, "stderr")

        try:
            image_dir.mkdir(parents=True, exist_ok=True)

            if mode in ("all", "extract"):
                print("\n[STEP 1] Extracting PRC images from factsheet PDFs...")
                extract_prc.process_folder(
                    input_dir=str(input_dir),
                    output_dir=str(image_dir),
                    zoom=zoom
                )
                print("[STEP 1] Image extraction finished.")

            if mode in ("all", "ocr"):
                print("\n[STEP 2] Reading extracted images and generating Excel...")
                excel.parent.mkdir(parents=True, exist_ok=True)

                # Keep debug output beside the extracted images instead of the launch directory.
                Main_PRC.DEBUG_FOLDER = str(image_dir / "PRC_Debug_Output")
                Main_PRC.process_prc_folder_with_easyocr(
                    root_folder=str(image_dir),
                    scheme_master_path=str(master) if master else None,
                    scheme_master_fund_col=fund_column,
                    output_excel=str(excel),
                    debug=debug
                )
                if not excel.is_file():
                    raise RuntimeError(
                        "Processing ended but the Excel file was not created. "
                        "Check the log for missing images, EasyOCR, or dependency errors."
                    )
                print(f"[STEP 2] Excel created: {excel}")

            self.events.put(("done", (True, mode, str(excel) if excel else str(image_dir))))
        except Exception:
            traceback.print_exc()
            self.events.put(("done", (False, mode, "")))
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr

    def _drain_events(self):
        try:
            while True:
                event_type, payload = self.events.get_nowait()
                if event_type in ("stdout", "stderr"):
                    self._append_log(payload, event_type)
                elif event_type == "done":
                    ok, mode, output = payload
                    self._set_running(False)
                    if ok:
                        self._append_log("\nJob completed successfully.\n", "success")
                        self.status.set("Completed")
                        messagebox.showinfo("Completed", f"PRC {mode} job completed.\n\nOutput:\n{output}")
                    else:
                        self._append_log("\nJob failed. Review the error log above.\n", "stderr")
                        self.status.set("Failed")
                        messagebox.showerror("Failed", "The PRC job failed. Review the live log for details.")
        except queue.Empty:
            pass
        finally:
            self.after(100, self._drain_events)

    def _set_running(self, running):
        state = "disabled" if running else "normal"
        for button in (self.run_all_button, self.extract_button, self.ocr_button):
            button.configure(state=state)
        if running:
            self.status.set("Processing...")
            self.progress.start(10)
        else:
            self.progress.stop()

    def _append_log(self, text, tag=None):
        self.log.configure(state="normal")
        self.log.insert("end", text, tag)
        self.log.see("end")
        self.log.configure(state="disabled")

    def _clear_log(self):
        self.log.configure(state="normal")
        self.log.delete("1.0", "end")
        self.log.configure(state="disabled")

    def _on_close(self):
        if self.worker and self.worker.is_alive():
            if not messagebox.askyesno(
                "Processing is active",
                "A job is still running. Closing now will stop the UI and may leave partial output. Close anyway?"
            ):
                return
        self.destroy()


if __name__ == "__main__":
    app = PRCAutomationUI()
    app.mainloop()
